pipelines:
  tags:
    '*':
      - step:
          runs-on:
            - self.hosted
            - linux
          name: Build payggo image
          image: docker:latest
          script:
            - export DOCKER_HOST=""
            - docker build -t payggo .
            - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            - docker tag payggo "$DOCKER_USERNAME/payggo-backend:$BITBUCKET_TAG"
            - docker push "$DOCKER_USERNAME/payggo-backend:$BITBUCKET_TAG"