version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    user: 0:0
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8030:80'
