<?php


namespace app\api\v1\controllers;


use app\models\User;
use app\services\UserService;
use yii\filters\Cors;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;


class UserController extends SafeController
{
    public $modelClass = User::class;
    /**
     * @var UserService
     */
    private UserService $userService;

    public function __construct($id, $module, UserService $userService, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->userService = $userService;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->user->enableSession = false;
    }

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'cors' => [
                'class' => Cors::class
            ],
        ]);
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['create']);
        return $actions;
    }

    public function actionCreate()
    {
        if (\Yii::$app->user->isGuest) {
            throw new BadRequestHttpException();
        }
        $post = $this->request->post();
        $this->userService->createUser($post);
        $this->response->setStatusCode(201);
        $this->response->content = '';
    }

    public function actionChangePassword()
    {
        $post = $this->request->post();
        $this->userService->changePassword(\Yii::$app->user->id, $post);
        $this->response->setStatusCode(201);
        $this->response->content = '';
    }
}
